name: PEYTONHOME & THE MDC
favicon: null
layout_spectrum: 0.4889173188712448
typography_spectrum: 0.18743902095593512
title: INTERIOR DESIGN SHOWROOMS . TO THE DESIGN TRADE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d3d0'
    - '#b0a8a6'
    - '#7f7a77'
    - '#292b16'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.5852883150801063
  saturation: 0.804454283323139
  rhythmicContrast: 0.2747925173025578
purpose: []
